# cloudbuild.yaml

options:
  substitutionOption: ALLOW_LOOSE

  # A) bucket regional user-owned
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

  # ——— oppure ———
  # B) solo Cloud Logging
  # logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "europe-west12"

images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA",
        "."
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region=$_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
