# cloudbuild.yaml
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY    # <-- qui

substitutions:
  _REGION: "europe-west1"
  _SERVICE: "my-api"

images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"
      - .

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
