options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "us-east1"
  _INSTANCE: "cloud-palestra-athena:us-east1:root"

steps:
  # 0) Build immagine con Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA","."]

  # 1) PUSH esplicito dell'immagine (necessario PRIMA del deploy)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push","gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA"]

  # 2) Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances $_INSTANCE \
          --set-env-vars CLOUD_SQL_CONNECTION_NAME=$_INSTANCE,DB_SOCKET=/cloudsql/$_INSTANCE,DB_NAME=fitness_db,DB_USER=palestra_athena,DB_PASS=P@lestra_Athena25

# (facoltativo) lasciarlo non fa male, ma ormai abbiamo fatto il push nello step 1
images:
  - "gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA"

timeout: "1200s"
