options:
  substitutionOption: ALLOW_LOOSE
  # se vuoi gestire i log in un bucket regionale di tua proprietà:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # 1) Costruisci l’immagine dal Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$SERVICE:$COMMIT_SHA"
      - "."

  # 2) (implicit) il push dell’immagine è gestito da `images:` qui sotto

  # 3) Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy webapppalestra \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region=us-east1 \
          --platform=managed \
          --allow-unauthenticated \
          --add-cloudsql-instances cloud-palestra-athena:europe-west1:fitness-db

# Indica quali immagini caricare nel registry
images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

timeout: "1200s"
