# cloudbuild.yaml
options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _REGION: "europe-west1"
  _SERVICE: "my-api"                # il nome del tuo servizio Cloud Run
images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

steps:
  # 1) Costruisci l’immagine con tag basato sul commit
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA",
        "."
      ]

  # 2) Push dell’immagine (implicitamente fatto da Cloud Build grazie a `images:`)

  # 3) Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
