options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "europe-west1"
  _SERVICE: "webapppalestra"

# L’immagine andrà in Artifact Registry
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$COMMIT_SHA"

steps:
  # 1) Build Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$COMMIT_SHA",
        "."
      ]

  # 2) Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
