options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "europe-west12"   # solo per il deploy

images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA", "."]

  # (push è automatico perché hai images:)

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated
timeout: "1200s"
