# cloudbuild.yaml
# options:
#   substitutionOption: ALLOW_LOOSE
#   default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# substitutions:
#   _SERVICE: "webapppalestra"
#   _REGION: "europe-west12"

# steps:
#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: "bash"
#     args:
#       - "-c"
#       - |
#         gcloud run deploy $_SERVICE \
#           --source . \
#           --region=$_REGION \
#           --platform managed \
#           --allow-unauthenticated

# timeout: "1200s"


options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "europe-west12"

steps:
  # 1) Costruisci l’immagine col Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA", "."]
  # 2) Push (implicitamente gestito da `images:`)
images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

  # 3) Deploy
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region=$_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
