options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "us-east1"
  _INSTANCE: "cloud-palestra-athena:us-east1:root"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA","."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push","gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances $_INSTANCE \
          --set-env-vars CLOUD_SQL_CONNECTION_NAME=$_INSTANCE,DB_SOCKET=/cloudsql/$_INSTANCE,DB_NAME=fitness_db,DB_USER=palestra_athena \
          --set-secrets DB_PASS=db-pass:latest,API_KEY=api-key:latest,FIREBASE_CREDENTIALS_JSON=firebase-admin-sa:latest

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE:$COMMIT_SHA"

timeout: "1200s"
