# cloudbuild.yaml
options:
  substitutionOption: ALLOW_LOOSE
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE: "webapppalestra"
  _REGION: "europe-west12"

steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --source . \
          --region=$_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
