# cloudbuild.yaml
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "europe-west1"
  _SERVICE: "my-api"

images:
  - "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA"

steps:
  # 1) Costruisci l’immagine
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA",
        "."
      ]

  # 2) Deploy su Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/webapppalestra:$COMMIT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated

timeout: "1200s"
